### ISSUE TITLE
endpointのアイコンが不適切

### ISSUE THREAD

**Issue by iselegant** [shigeru-oda/jawsdays2022-container-handson#2]
###  Issue

nitpickなコメントで恐縮ですが、構成図にて利用されているEndpointのアイコンが異なるようです。
このアイコンはAPI Gatewayに関するエンドポイントリソースを表すために利用するものです。

https://github.com/shigeru-oda/jawsdays2022-container-handson/blob/main/image/drowio-2-1.png

### Improvement

おそらくこのケースではインタフェース型VPC endpointを意味しているかと推察しており、次のアイコンの利用が正しいです。
<img width="37" alt="スクリーンショット 2022-09-14 10 04 04" src="https://user-images.githubusercontent.com/30573608/190035681-fb707d63-8f78-47ac-9f59-5425fec88a3d.png">

**Comment by shigeru-oda** [comment]
VPCエンドポイントのアイコンに修正しました。
https://github.com/shigeru-oda/jawsdays2022-container-handson/blob/main/image/drowio-2-1.png

**Comment by shigeru-oda** [comment]
手順書の前半のみ対応しております、後半は別途対応します。

**Comment by iselegant** [comment]
LGTM🚀
※手順書の後半も修正されているようでしたｂ
