### ISSUE TITLE
用語の修正：Fargateクラスター

### ISSUE THREAD

**Issue by iselegant** [shigeru-oda/jawsdays2022-container-handson#3]
### Issue

AWS Fargateはコンテナワークロードにおけるデータプレーンの機能を提供します。
言い換えれば、コンテナにかかるオーケストレーション機能やクラスター構成に関する責務は追いません。

そのため、Fargateクラスターというキーワードは通常利用されません。
https://github.com/shigeru-oda/jawsdays2022-container-handson/blob/main/image/drowio-2-1.png

### Improvement

今回のハンズオンではECSを利用されると理解しています。
そのため、アイコン含めてECSクラスターと表現する方が適切＆誤解を生まないと考えています。
※一方、Fargateを利用する場合のタスクはFargateタスクと表現することがあります。Fargateの文脈を伝えるなら、Fargateタスクと表現しても問題ないはず。

**Comment by shigeru-oda** [comment]
ご指摘ありがとうございます。

ECSクラスターとして修正しました。
[https://github.com/shigeru-oda/jawsdays2022-container-handson/blob/main/image/drowio-2-1.png](https://github.com/shigeru-oda/jawsdays2022-container-handson/blob/main/image/drowio-2-1.png)

以下を参考に修正しております。
https://aws.amazon.com/jp/cdp/ec-container/

**Comment by shigeru-oda** [comment]
手順書の前半のみ対応しております、後半は別途対応します。

**Comment by iselegant** [comment]
LGTM🚀
