### ISSUE TITLE
typo?: VPCを使ったネットワーク関係の構築

### ISSUE THREAD

**Issue by iselegant** [shigeru-oda/jawsdays2022-container-handson#4]
### Issues

VPCを使ったネットワーク関係の構築　→　VPCを使ったネットワーク**環境**の構築
の間違い？

**Comment by shigeru-oda** [comment]
詳細まで確認ありがとうございます。
対応しました。

https://shigeru-oda.github.io/jawsdays2022-container-handson/docs/#1

**Comment by shigeru-oda** [comment]
ご確認頂いた後にCloseします。

**Comment by iselegant** [comment]
LGTM🚀
