### ISSUE TITLE
利用ブラウザについて

### ISSUE THREAD

**Issue by shigeru-oda** [shigeru-oda/jawsdays2022-container-handson#5]
From 尾谷さん

Safari でやってて、Cloud 9 でプレビュー時に以下が表示されて
Opps! ってなりました。
> You can't access preview functionality because your browser blocks third-party cookies (also known as cross-site tracking). To use previews, allow third-party cookies and reload your IDE.

**Comment by shigeru-oda** [comment]
ブラウザ指定を「ご挨拶」に追加しました。

↓

■ブラウザについて
Chrome もしくは Firefoxをご利用下さい。
IE もしくは Safariでは正しい挙動にならない可能性がございます

**Comment by otanikohei** [comment]
ありがとうございます。確認しました。
