### ISSUE TITLE
ecsTaskExecutionRoleの削除について

### ISSUE THREAD

**Issue by shigeru-oda** [shigeru-oda/jawsdays2022-container-handson#6]
削除手順
IAM ロール：ecsTaskExecutionRole も必要。

**Comment by shigeru-oda** [comment]
ecsTaskExecutionRoleは画面コンソールで自動的に作られるので削除対象外としてました
任意で消す流れにします。
https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/task_execution_IAM_role.html


■IAM（任意）
ロール > ecsTaskExecutionRole > 削除
ecsTaskExecutionRoleは、画面コンソールでのECSのタスク定義作成時に、「新しいロールの作成」を選択する自動的に作成されます。今後もECSサービスを利用するのであれば、残しておいても問題ないです。
[Amazon ECS タスク実行IAM ロール](https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/task_execution_IAM_role.html)

**Comment by otanikohei** [comment]
ありがとうございます。確認しました。
